# 支持的数据类型
# 初始阶段只使用f32，后续可以扩展到其他类型

supported_dtypes:
  - f32    # 32位浮点数
  # - f16    # 16位浮点数 (后续扩展)
  # - i32    # 32位整数 (后续扩展)
  # - i8     # 8位整数 (后续扩展)

# 默认数据类型
default_dtype: f32

# 类型转换规则
type_conversions:
  f32_to_f16: "arith.extf"
  f16_to_f32: "arith.extf"
  i32_to_f32: "arith.sitofp"
  f32_to_i32: "arith.fptosi"
